/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphplotter;

import graphplotter.ui.components.CanvasPanel;
import graphplotter.ui.components.CoordinateSystem;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.GroupLayout;

/**
 *
 * @author Denis
 */
public class WindowWrapper extends javax.swing.JPanel {

    /**
     * Creates new form WindowWrapper
     */
    public WindowWrapper() {
        initComponents();
        initCustomComponents();
    }

    private void initCustomComponents(){
        Dimension s = canvasPanel1.getSize();
        System.out.println("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        visibilityPanel = new javax.swing.JPanel();
        sineVisibilityBox = new javax.swing.JCheckBox();
        cosineVisibilityBox = new javax.swing.JCheckBox();
        diffBox = new javax.swing.JCheckBox();
        filterPanel = new javax.swing.JPanel();
        filterApplyBtn = new javax.swing.JButton();
        firstFilterInput = new javax.swing.JTextField();
        secondFilterInput = new javax.swing.JTextField();
        thirdFilterInput = new javax.swing.JTextField();
        forthFilterInput = new javax.swing.JTextField();
        fifthFilterInput = new javax.swing.JTextField();
        firstFilterLabel = new javax.swing.JLabel();
        secondFilterLabel = new javax.swing.JLabel();
        thirdFilterLabel = new javax.swing.JLabel();
        forthFilterLabel = new javax.swing.JLabel();
        fifthFilterLabel = new javax.swing.JLabel();
        scalePanel = new javax.swing.JPanel();
        scaleChangeBtn = new javax.swing.JButton();
        devidentInput = new javax.swing.JTextField();
        devisorInput = new javax.swing.JTextField();
        dashLabel = new javax.swing.JLabel();
        canvasPanel1 = new graphplotter.ui.components.CanvasPanel();

        menuPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        visibilityPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Visibility"));

        sineVisibilityBox.setText("Sine");
        sineVisibilityBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sineVisibilityBoxActionPerformed(evt);
            }
        });

        cosineVisibilityBox.setText("Cosine");
        cosineVisibilityBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosineVisibilityBoxActionPerformed(evt);
            }
        });

        diffBox.setText("Diff");
        diffBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diffBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout visibilityPanelLayout = new javax.swing.GroupLayout(visibilityPanel);
        visibilityPanel.setLayout(visibilityPanelLayout);
        visibilityPanelLayout.setHorizontalGroup(
            visibilityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visibilityPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(visibilityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sineVisibilityBox)
                    .addComponent(cosineVisibilityBox)
                    .addComponent(diffBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        visibilityPanelLayout.setVerticalGroup(
            visibilityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visibilityPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sineVisibilityBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cosineVisibilityBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(diffBox)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        filterPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Filter"));

        filterApplyBtn.setText("Apply");
        filterApplyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterApplyBtnActionPerformed(evt);
            }
        });

        firstFilterLabel.setText("F1");

        secondFilterLabel.setText("F2");

        thirdFilterLabel.setText("F3");

        forthFilterLabel.setText("F5");

        fifthFilterLabel.setText("F4");

        javax.swing.GroupLayout filterPanelLayout = new javax.swing.GroupLayout(filterPanel);
        filterPanel.setLayout(filterPanelLayout);
        filterPanelLayout.setHorizontalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filterApplyBtn)
                    .addGroup(filterPanelLayout.createSequentialGroup()
                        .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(filterPanelLayout.createSequentialGroup()
                                .addComponent(firstFilterInput, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(secondFilterInput, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(thirdFilterInput, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(forthFilterInput, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(filterPanelLayout.createSequentialGroup()
                                .addComponent(firstFilterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(secondFilterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(thirdFilterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fifthFilterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(forthFilterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fifthFilterInput, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        filterPanelLayout.setVerticalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filterPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstFilterLabel)
                    .addComponent(secondFilterLabel)
                    .addComponent(thirdFilterLabel)
                    .addComponent(forthFilterLabel)
                    .addComponent(fifthFilterLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstFilterInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondFilterInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thirdFilterInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(forthFilterInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fifthFilterInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filterApplyBtn)
                .addContainerGap())
        );

        scalePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Scale"));

        scaleChangeBtn.setText("Change");
        scaleChangeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scaleChangeBtnActionPerformed(evt);
            }
        });

        dashLabel.setText("/");

        javax.swing.GroupLayout scalePanelLayout = new javax.swing.GroupLayout(scalePanel);
        scalePanel.setLayout(scalePanelLayout);
        scalePanelLayout.setHorizontalGroup(
            scalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scalePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(scalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(scalePanelLayout.createSequentialGroup()
                        .addComponent(scaleChangeBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(scalePanelLayout.createSequentialGroup()
                        .addComponent(devidentInput, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dashLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(devisorInput)
                        .addGap(14, 14, 14))))
        );
        scalePanelLayout.setVerticalGroup(
            scalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, scalePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(scalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(devidentInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dashLabel)
                    .addComponent(devisorInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scaleChangeBtn)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(visibilityPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(filterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scalePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addComponent(visibilityPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scalePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        canvasPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(canvasPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(canvasPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void filterApplyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterApplyBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filterApplyBtnActionPerformed

    private void scaleChangeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scaleChangeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scaleChangeBtnActionPerformed

    private void sineVisibilityBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sineVisibilityBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sineVisibilityBoxActionPerformed

    private void cosineVisibilityBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosineVisibilityBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cosineVisibilityBoxActionPerformed

    private void diffBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diffBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diffBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private graphplotter.ui.components.CanvasPanel canvasPanel1;
    private javax.swing.JCheckBox cosineVisibilityBox;
    private javax.swing.JLabel dashLabel;
    private javax.swing.JTextField devidentInput;
    private javax.swing.JTextField devisorInput;
    private javax.swing.JCheckBox diffBox;
    private javax.swing.JTextField fifthFilterInput;
    private javax.swing.JLabel fifthFilterLabel;
    private javax.swing.JButton filterApplyBtn;
    private javax.swing.JPanel filterPanel;
    private javax.swing.JTextField firstFilterInput;
    private javax.swing.JLabel firstFilterLabel;
    private javax.swing.JTextField forthFilterInput;
    private javax.swing.JLabel forthFilterLabel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton scaleChangeBtn;
    private javax.swing.JPanel scalePanel;
    private javax.swing.JTextField secondFilterInput;
    private javax.swing.JLabel secondFilterLabel;
    private javax.swing.JCheckBox sineVisibilityBox;
    private javax.swing.JTextField thirdFilterInput;
    private javax.swing.JLabel thirdFilterLabel;
    private javax.swing.JPanel visibilityPanel;
    // End of variables declaration//GEN-END:variables
}
